-- Databricks notebook source
-- MAGIC %md
-- MAGIC Matt Cutini on 20250811: This notebook is a carry-over from the old accelerator notebook '2-omop531-cdm-setup' and will be deleted after the code here is merged with the code from the old notebook '4-omop531-etl-synthea' and turned into a Lakeflow Declarative Pipeline. Please see notebook '06-omop542-etl-synthea' for the beginnings of that Lakeflow Declarative Pipeline. 
-- MAGIC
-- MAGIC Matt Cutini on 20250812: The create table statements that are still in this notebook have no corresponding create materialized view statements in notebook '06-omop542-etl-synthea' and so the logic for those create materialized view statements will need to be written.

-- COMMAND ----------

-- CREATE
-- OR REPLACE TABLE METADATA (
--   METADATA_ID LONG, -- New field in version 5.4.2
--   METADATA_CONCEPT_ID LONG,
--   METADATA_TYPE_CONCEPT_ID LONG,
--   NAME STRING,
--   VALUE_AS_STRING STRING,
--   VALUE_AS_CONCEPT_ID LONG,
--   VALUE_AS_NUMBER DOUBLE, -- New field in version 5.4.2
--   METADATA_DATE DATE,
--   METADATA_DATETIME TIMESTAMP
-- ) USING DELTA;

-- COMMAND ----------

-- CREATE
-- OR REPLACE TABLE VISIT_DETAIL (
--   VISIT_DETAIL_ID LONG,
--   PERSON_ID LONG,
--   VISIT_DETAIL_CONCEPT_ID LONG,
--   VISIT_DETAIL_START_DATE DATE,
--   VISIT_DETAIL_START_DATETIME TIMESTAMP,
--   VISIT_DETAIL_END_DATE DATE,
--   VISIT_DETAIL_END_DATETIME TIMESTAMP,
--   VISIT_DETAIL_TYPE_CONCEPT_ID LONG,
--   PROVIDER_ID LONG,
--   CARE_SITE_ID LONG,
--   VISIT_DETAIL_SOURCE_VALUE STRING,
--   VISIT_DETAIL_SOURCE_CONCEPT_ID LONG,
--   ADMITTED_FROM_CONCEPT_ID LONG, -- Field name changed in version 5.4.2
--   ADMITTED_FROM_SOURCE_VALUE STRING, -- Field name changed in version 5.4.2
--   DISCHARGED_TO_SOURCE_VALUE STRING, -- Field name changed in version 5.4.2
--   DISCHARGED_TO_CONCEPT_ID LONG, -- Field name changed in version 5.4.2
--   PRECEDING_VISIT_DETAIL_ID LONG,
--   PARENT_VISIT_DETAIL_ID LONG, -- Field name changed in version 5.4.2
--   VISIT_OCCURRENCE_ID LONG
-- ) USING DELTA;

-- COMMAND ----------

-- CREATE
-- OR REPLACE TABLE DEVICE_EXPOSURE (
--   DEVICE_EXPOSURE_ID LONG,
--   PERSON_ID LONG,
--   DEVICE_CONCEPT_ID LONG,
--   DEVICE_EXPOSURE_START_DATE DATE,
--   DEVICE_EXPOSURE_START_DATETIME TIMESTAMP,
--   DEVICE_EXPOSURE_END_DATE DATE,
--   DEVICE_EXPOSURE_END_DATETIME TIMESTAMP,
--   DEVICE_TYPE_CONCEPT_ID LONG,
--   UNIQUE_DEVICE_ID STRING,
--   PRODUCTION_ID LONG, -- New column in version 5.4.2
--   QUANTITY LONG,
--   PROVIDER_ID LONG,
--   VISIT_OCCURRENCE_ID LONG,
--   VISIT_DETAIL_ID LONG,
--   DEVICE_SOURCE_VALUE STRING,
--   DEVICE_SOURCE_CONCEPT_ID LONG, 
--   UNIT_CONCEPT_ID LONG, -- New column in version 5.4.2
--   UNIT_SOURCE_VALUE STRING, -- New column in version 5.4.2
--   UNIT_SOURCE_CONCEPT_ID LONG -- New column in version 5.4.2
-- ) USING DELTA;

-- COMMAND ----------

-- CREATE
-- OR REPLACE TABLE NOTE (
--   NOTE_ID LONG,
--   PERSON_ID LONG,
--   NOTE_DATE DATE,
--   NOTE_DATETIME TIMESTAMP,
--   NOTE_TYPE_CONCEPT_ID LONG,
--   NOTE_CLASS_CONCEPT_ID LONG,
--   NOTE_TITLE STRING,
--   NOTE_TEXT STRING,
--   ENCODING_CONCEPT_ID LONG,
--   LANGUAGE_CONCEPT_ID LONG,
--   PROVIDER_ID LONG,
--   VISIT_OCCURRENCE_ID LONG,
--   VISIT_DETAIL_ID LONG,
--   NOTE_SOURCE_VALUE STRING,
--   NOTE_EVENT_ID LONG, -- New column in version 5.4.2
--   NOTE_EVENT_FIELD_CONCEPT_ID LONG -- New column in version 5.4.2
-- ) USING DELTA;

-- COMMAND ----------

-- CREATE
-- OR REPLACE TABLE NOTE_NLP (
--   NOTE_NLP_ID LONG,
--   NOTE_ID LONG,
--   SECTION_CONCEPT_ID LONG,
--   SNIPPET STRING,
--   OFFSET STRING,
--   LEXICAL_VARIANT STRING,
--   NOTE_NLP_CONCEPT_ID LONG,
--   NOTE_NLP_SOURCE_CONCEPT_ID LONG,
--   NLP_SYSTEM STRING,
--   NLP_DATE DATE,
--   NLP_DATETIME TIMESTAMP,
--   TERM_EXISTS STRING,
--   TERM_TEMPORAL STRING,
--   TERM_MODIFIERS STRING
-- ) USING DELTA;

-- COMMAND ----------

-- CREATE
-- OR REPLACE TABLE OBSERVATION (
--   OBSERVATION_ID LONG,
--   PERSON_ID LONG,
--   OBSERVATION_CONCEPT_ID LONG,
--   OBSERVATION_DATE DATE,
--   OBSERVATION_DATETIME TIMESTAMP,
--   OBSERVATION_TYPE_CONCEPT_ID LONG,
--   VALUE_AS_NUMBER DOUBLE,
--   VALUE_AS_STRING STRING,
--   VALUE_AS_CONCEPT_ID LONG,
--   QUALIFIER_CONCEPT_ID LONG,
--   UNIT_CONCEPT_ID LONG,
--   PROVIDER_ID LONG,
--   VISIT_OCCURRENCE_ID LONG,
--   VISIT_DETAIL_ID LONG,
--   OBSERVATION_SOURCE_VALUE STRING,
--   OBSERVATION_SOURCE_CONCEPT_ID LONG,
--   UNIT_SOURCE_VALUE STRING,
--   QUALIFIER_SOURCE_VALUE STRING,
--   VALUE_SOURCE_VALUE STRING, -- New column in version 5.4.2
--   OBSERVATION_EVENT_ID LONG, -- New column in version 5.4.2
--   OBS_EVENT_FIELD_CONCEPT_ID LONG -- New column in version 5.4.
-- ) USING DELTA;

-- COMMAND ----------

-- CREATE
-- OR REPLACE TABLE SPECIMEN (
--   SPECIMEN_ID LONG,
--   PERSON_ID LONG,
--   SPECIMEN_CONCEPT_ID LONG,
--   SPECIMEN_TYPE_CONCEPT_ID LONG,
--   SPECIMEN_DATE DATE,
--   SPECIMEN_DATETIME TIMESTAMP,
--   QUANTITY DOUBLE,
--   UNIT_CONCEPT_ID LONG,
--   ANATOMIC_SITE_CONCEPT_ID LONG,
--   DISEASE_STATUS_CONCEPT_ID LONG,
--   SPECIMEN_SOURCE_ID STRING,
--   SPECIMEN_SOURCE_VALUE STRING,
--   UNIT_SOURCE_VALUE STRING,
--   ANATOMIC_SITE_SOURCE_VALUE STRING,
--   DISEASE_STATUS_SOURCE_VALUE STRING
-- ) USING DELTA;

-- COMMAND ----------

-- CREATE
-- OR REPLACE TABLE FACT_RELATIONSHIP (
--   DOMAIN_CONCEPT_ID_1 LONG,
--   FACT_ID_1 LONG,
--   DOMAIN_CONCEPT_ID_2 LONG,
--   FACT_ID_2 LONG,
--   RELATIONSHIP_CONCEPT_ID LONG
-- ) USING DELTA;

-- COMMAND ----------

-- CREATE
-- OR REPLACE TABLE DEATH (
--   PERSON_ID LONG,
--   DEATH_DATE DATE,
--   DEATH_DATETIME TIMESTAMP,
--   DEATH_TYPE_CONCEPT_ID LONG,
--   CAUSE_CONCEPT_ID LONG,
--   CAUSE_SOURCE_VALUE STRING,
--   CAUSE_SOURCE_CONCEPT_ID LONG
-- ) USING DELTA;

-- COMMAND ----------

-- CREATE
-- OR REPLACE TABLE LOCATION (
--   LOCATION_ID LONG,
--   ADDRESS_1 STRING,
--   ADDRESS_2 STRING,
--   CITY STRING,
--   STATE STRING,
--   ZIP STRING,
--   COUNTY STRING,
--   LOCATION_SOURCE_VALUE STRING,
--   COUNTRY_CONCEPT_ID LONG, -- New column in version 5.4.2
--   COUNTRY_SOURCE_VALUE STRING, -- New column in version 5.4.2
--   LATITUDE DOUBLE, -- New column in version 5.4.2
--   LONGITUDE DOUBLE -- New column in version 5.4.2
-- ) USING DELTA;

-- COMMAND ----------

-- CREATE
-- OR REPLACE TABLE CARE_SITE (
--   CARE_SITE_ID LONG,
--   CARE_SITE_NAME STRING,
--   PLACE_OF_SERVICE_CONCEPT_ID LONG,
--   LOCATION_ID LONG,
--   CARE_SITE_SOURCE_VALUE STRING,
--   PLACE_OF_SERVICE_SOURCE_VALUE STRING
-- ) USING DELTA;

-- COMMAND ----------

-- CREATE
-- OR REPLACE TABLE PROVIDER (
--   PROVIDER_ID LONG,
--   PROVIDER_NAME STRING,
--   NPI STRING,
--   DEA STRING,
--   SPECIALTY_CONCEPT_ID LONG,
--   CARE_SITE_ID LONG,
--   YEAR_OF_BIRTH LONG,
--   GENDER_CONCEPT_ID LONG,
--   PROVIDER_SOURCE_VALUE STRING,
--   SPECIALTY_SOURCE_VALUE STRING,
--   SPECIALTY_SOURCE_CONCEPT_ID LONG,
--   GENDER_SOURCE_VALUE STRING,
--   GENDER_SOURCE_CONCEPT_ID LONG
-- ) USING DELTA;

-- COMMAND ----------

-- CREATE
-- OR REPLACE TABLE PAYER_PLAN_PERIOD (
--   PAYER_PLAN_PERIOD_ID LONG,
--   PERSON_ID LONG,
--   PAYER_PLAN_PERIOD_START_DATE DATE,
--   PAYER_PLAN_PERIOD_END_DATE DATE,
--   PAYER_CONCEPT_ID LONG,
--   PAYER_SOURCE_VALUE STRING,
--   PAYER_SOURCE_CONCEPT_ID LONG,
--   PLAN_CONCEPT_ID LONG,
--   PLAN_SOURCE_VALUE STRING,
--   PLAN_SOURCE_CONCEPT_ID LONG,
--   SPONSOR_CONCEPT_ID LONG,
--   SPONSOR_SOURCE_VALUE STRING,
--   SPONSOR_SOURCE_CONCEPT_ID LONG,
--   FAMILY_SOURCE_VALUE STRING,
--   STOP_REASON_CONCEPT_ID LONG,
--   STOP_REASON_SOURCE_VALUE STRING,
--   STOP_REASON_SOURCE_CONCEPT_ID LONG
-- ) USING DELTA;

-- COMMAND ----------

-- CREATE
-- OR REPLACE TABLE COST (
--   COST_ID LONG,
--   COST_EVENT_ID LONG,
--   COST_DOMAIN_ID STRING,
--   COST_TYPE_CONCEPT_ID LONG,
--   CURRENCY_CONCEPT_ID LONG,
--   TOTAL_CHARGE DOUBLE,
--   TOTAL_COST DOUBLE,
--   TOTAL_PAID DOUBLE,
--   PAID_BY_PAYER DOUBLE,
--   PAID_BY_PATIENT DOUBLE,
--   PAID_PATIENT_COPAY DOUBLE,
--   PAID_PATIENT_COINSURANCE DOUBLE,
--   PAID_PATIENT_DEDUCTIBLE DOUBLE,
--   PAID_BY_PRIMARY DOUBLE,
--   PAID_INGREDIENT_COST DOUBLE,
--   PAID_DISPENSING_FEE DOUBLE,
--   PAYER_PLAN_PERIOD_ID LONG,
--   AMOUNT_ALLOWED DOUBLE,
--   REVENUE_CODE_CONCEPT_ID LONG,
--   REVENUE_CODE_SOURCE_VALUE STRING,
--   DRG_CONCEPT_ID LONG,
--   DRG_SOURCE_VALUE STRING
-- ) USING DELTA;

-- COMMAND ----------

-- CREATE
-- OR REPLACE TABLE DOSE_ERA (
--   DOSE_ERA_ID LONG,
--   PERSON_ID LONG,
--   DRUG_CONCEPT_ID LONG,
--   UNIT_CONCEPT_ID LONG,
--   DOSE_VALUE DOUBLE,
--   DOSE_ERA_START_DATE DATE,
--   DOSE_ERA_END_DATE DATE
-- ) USING DELTA;

-- COMMAND ----------

-- CREATE
-- OR REPLACE TABLE cohort (
--   cohort_definition_id LONG,
--   subject_id LONG,
--   cohort_start_date DATE,
--   cohort_end_date DATE
-- ) USING DELTA;

-- COMMAND ----------

-- CREATE
-- OR REPLACE TABLE cohort_definition (
--   cohort_definition_id LONG,
--   cohort_definition_name STRING,
--   cohort_definition_description STRING,
--   definition_type_concept_id LONG,
--   cohort_definition_syntax STRING,
--   subject_concept_id LONG,
--   cohort_initiation_date DATE
-- ) USING DELTA;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Check OMOP 5.4.2 Metadata Version

-- COMMAND ----------

-- INSERT INTO METADATA
-- VALUES
--   (
--     0,
--     0,
--     0,
--     'OHDSI OMOP CDM Version',
--     '5.4.2',
--     0,
--     0,
--     CURRENT_DATE(),
--     CURRENT_TIMESTAMP()
--      );

-- COMMAND ----------

-- SELECT * FROM metadata;
